spring:
  application:
    name: sshop-stock
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        group: STOCK_GROUP
      config:
        server-addr: http://127.0.0.1:8848
        file-extension: yaml
        group: STOCK_GROUP

  ##数据库配置
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sshop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8


mybatis-plus:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config.db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0



server:
  port: 8611

logging:
  config: classpath:logback.xml

