spring:
  application:
    name: sshop-stock
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        group: SSHOP_GROUP
      config:
        server-addr: http://127.0.0.1:8848
        file-extension: yaml
        group: SSHOP_GROUP

  ##数据库配置
  datasource:
    username: fangzehua
    password: fangzehua
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vbn7y8nezwvp5bw3xo.mysql.zhangbei.rds.aliyuncs.com:3306/sshop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true


mybatis-plus:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config.db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0



server:
  port: 8622

logging:
  config: classpath:logback.xml

