spring:
  application:
    name: sshop-admin
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        group: SSHOP_GROUP
      config:
        server-addr: http://127.0.0.1:8848
        file-extension: yaml
        group: SSHOP_GROUP
  redis:
    database: 13
    host: 39.100.230.127
    port: 6379
    password: jika_009_x!@
    timeout: 500

  ##数据库配置
  datasource:
    username: fangzehua
    password: fangzehua
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vbn7y8nezwvp5bw3xo.mysql.zhangbei.rds.aliyuncs.com:3306/sshop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true


  rabbitmq:
    host: 39.100.230.127
    port: 5672
    username: fzh
    password: fzh123
    publisher-confirms: true #发送回调
    publisher-returns: true  #失败回调
    listener:
      max-concurrency: 100
      acknowledge-mode: manual
    template:
      mandatory: true


mybatis-plus:
  global-config.db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**.xml

server:
  port: 8611

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream




logging:
  config: classpath:logback.xml

