spring:
  application:
    name: sshop-payment
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.3:8848
        group: PAYMENT_GROUP
      config:
        server-addr: http://192.168.1.3:8848
        file-extension: yaml
        group: PAYMENT_GROUP

  ##数据库配置
  datasource:
    username: root
    password: jika009
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.100.230.127:3306/sshop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true


  profiles:
    active: dev


mybatis-plus:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config.db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0



server:
  port: 8655

logging:
  config: classpath:logback.xml

