spring:
  application:
    name: sshop-member #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.3:8848 #nacos注册地址
        group: DEFAULT_GROUP  #注册组 （服务组管理，不强制）
      config:
        server-addr: http://192.168.1.3:8848 #nacos注册地址
        file-extension: yaml #配置文件后缀支持 txt json yam xml html Properties 格式 大家更加喜欢来
        group: DEFAULT_GROUP # 分组 （配置组管理，不强制）

server:
  port: 8789

logging:
  config: classpath:logback.xml
